services:
  remedi:
    image: remedi:latest
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
       - database_data:/var/lib/postgresql/data

volumes:
  database_data: