name: Manual Docker Build and Push (Unstable)

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag"
        required: false
        default: "unstable"


jobs:
  build_and_push_unstable_docker:
    name: Build and Push Unstable to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ruitcatarino/remedi:${{ github.event.inputs.docker_tag }}
          target: prod
