name: Docker Build and Push

on:
  push:
    tags:
      - '*.*.*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: make test
  build_and_push:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build . -t ruitcatarino/remedi:${{ github.ref_name }} -t ruitcatarino/remedi:latest
      - name: push image to docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ruitcatarino --password-stdin
          docker push ruitcatarino/remedi:${{ github.ref_name }}
          docker push ruitcatarino/remedi:latest
