name: Python Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: make test
      - name: Upload coverage to coveralls.io
        run: uv run coveralls
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
